### PR TITLE
feat: add weather script to waybar

### LINKED ISSUE #163: Widget proposal + code - Weather
In case you consider adding it, here is the code. It autodetects your city:

~/.local/bin/waybar/wttr.py

```
#!/usr/bin/env python

import json
import requests
from datetime import datetime

WEATHER_CODES = {
    '113': '☀️',
    '116': '⛅️',
    '119': '☁️',
    '122': '☁️',
    '143': '🌫',
    '176': '🌦',
    '179': '🌧',
    '182': '🌧',
    '185': '🌧',
    '200': '⛈',
    '227': '🌨',
    '230': '❄️',
    '248': '🌫',
    '260': '🌫',
    '263': '🌦',
    '266': '🌦',
    '281': '🌧',
    '284': '🌧',
    '293': '🌦',
    '296': '🌦',
    '299': '🌧',
    '302': '🌧',
    '305': '🌧',
    '308': '🌧',
    '311': '🌧',
    '314': '🌧',
    '317': '🌧',
    '320': '🌨',
    '323': '🌨',
    '326': '🌨',
    '329': '❄️',
    '332': '❄️',
    '335': '❄️',
    '338': '❄️',
    '350': '🌧',
    '353': '🌦',
    '356': '🌧',
    '359': '🌧',
    '362': '🌧',
    '365': '🌧',
    '368': '🌨',
    '371': '❄️',
    '374': '🌧',
    '377': '🌧',
    '386': '⛈',
    '389': '🌩',
    '392': '⛈',
    '395': '❄️'
}

data = {}


weather = requests.get("https://wttr.in/?format=j1").json()


def format_time(time):
    return time.replace("00", "").zfill(2)


def format_temp(temp):
    return (hour['FeelsLikeC']+"°").ljust(3)


def format_chances(hour):
    chances = {
        "chanceoffog": "Fog",
        "chanceoffrost": "Frost",
        "chanceofovercast": "Overcast",
        "chanceofrain": "Rain",
        "chanceofsnow": "Snow",
        "chanceofsunshine": "Sunshine",
        "chanceofthunder": "Thunder",
        "chanceofwindy": "Wind"
    }

    conditions = []
    for event in chances.keys():
        if int(hour[event]) > 0:
            conditions.append(chances[event]+" "+hour[event]+"%")
    return ", ".join(conditions)


data['text'] = WEATHER_CODES[weather['current_condition'][0]['weatherCode']] + \
    " "+weather['current_condition'][0]['FeelsLikeC']+"°"

data['tooltip'] = f"<b>{weather['current_condition'][0]['weatherDesc'][0]['value']} {weather['current_condition'][0]['temp_C']}°</b>\n"
data['tooltip'] += f"Feels like: {weather['current_condition'][0]['FeelsLikeC']}°\n"
data['tooltip'] += f"Wind: {weather['current_condition'][0]['windspeedKmph']}Km/h\n"
data['tooltip'] += f"Humidity: {weather['current_condition'][0]['humidity']}%\n"
for i, day in enumerate(weather['weather']):
    data['tooltip'] += f"\n<b>"
    if i == 0:
        data['tooltip'] += "Today, "
    if i == 1:
        data['tooltip'] += "Tomorrow, "
    data['tooltip'] += f"{day['date']}</b>\n"
    data['tooltip'] += f"⬆️ {day['maxtempC']}° ⬇️ {day['mintempC']}° "
    data['tooltip'] += f"🌅 {day['astronomy'][0]['sunrise']} 🌇 {day['astronomy'][0]['sunset']}\n"
    for hour in day['hourly']:
        if i == 0:
            if int(format_time(hour['time'])) < datetime.now().hour-2:
                continue
        data['tooltip'] += f"{format_time(hour['time'])} {WEATHER_CODES[hour['weatherCode']]} {format_temp(hour['FeelsLikeC'])} {hour['weatherDesc'][0]['value']}, {format_chances(hour)}\n"


print(json.dumps(data))
```

Waybar config
```
    "custom/weather": {
      "icon-size": 42,
      "format": "{}",
      "tooltip": true,
      "on-click": "swaymsg exec 'foot -a scratchpad weather'",
      "interval": 3600,
      "exec": "waybar-wttr.py",
      "return-type": "json"
    },
```

Credits: bjesus
Original source code: https://gist.github.com/bjesus/f8db49e1434433f78e5200dc403d58a3

### PR DESCRIPTION
**Pull request by boredland**
closes https://github.com/Manjaro-Sway/manjaro-sway/issues/163

### CODE REVIEW

**Comment by Mathew-D** [comment]
I am trying the weather script but as I always have a vpn on the location is wrong.  I would love to be able to override the location. Also I am not sure right in the middle the bar is a good location.

**Comment by boredland** [comment]
> always have a vpn on the location is wrong

will add an optional override and a hint to the docs

**Comment by boredland** [comment]
> Also I am not sure right in the middle the bar is a good location.

where else? most left on right bar?

**Comment by Mathew-D** [comment]
Right bar would be a better location I think with the other tools we added.

**Comment by FallenChromium** [comment]
Actually the only way I can see the weather widget being tangible is exactly in the center, as it'll not interfere with the "functional" part of the bar. That said, it clearly indicates that documentation on how to move/remove it will be nice. (and, ideally, every other widget, though it's not really our domain, we shall redirect people to waybar docs then)

**Comment by FallenChromium** [comment]
I see the center location a bit more universal, because it's the way it works in GNOME, but it's just my opinion.

**Review by FallenChromium — APPROVED** [review]
Can't test atm, but if @Mathew-D will confirm that location changing works, it looks good to me!

**Comment by Mathew-D** [comment]
Yes the location argument works well.

**Review by Mathew-D — APPROVED** [review]

**Comment by boredland** [comment]
> That said, it clearly indicates that documentation on how to move/remove it will be nice. 

i mean, there is a more general note on waybar overrides and one explicit example (moving to bottom):
https://github.com/Manjaro-Sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-customize-waybar-without-losing-my-customization-after-an-upgrade

**Pull request merged**
