### PR TITLE
feat: add update script

### PR DESCRIPTION
**Pull request by boredland**
adds the update script from https://github.com/manjaro-sway/desktop-settings/pull/98 without using it.

we'd need to add fzf to desktop settings.

### CODE REVIEW

**Comment by boredland** [comment]
Open Questions:

- should we use topgrade instead of "just" yay?
- should we add it to the waybar?
- should we start it in a floating window?

**Comment by Mathew-D** [comment]
- topgrade looks interesting but I have never tried it before as anyone used it?
- as for waybar, maybe just the option to pick which upgrade method you want?
- yes I think a floating window would be best

**Comment by boredland** [comment]
> topgrade looks interesting but I have never tried it before as anyone used it?

I've been using it for a while now and its great - however I'm not convinced we should use it for a default updater script.

> as for waybar, maybe just the option to pick which upgrade method you want?

like a meta-script in the sway config checking a sway config variable?

> yes I think a floating window would be best

that should be easy.

**Comment by boredland** [comment]
one more thought: we could try to find a non-pamac tool to check up pending updates. one [script in aur](https://aur.archlinux.org/packages/checkupdates-aur) looks ok.

EDIT: pamac-cli is only 207kib installed and has few and unexotic dependencies, so probably we shouldn't worry about this.

EDIT2: we can just replace `pamac checkupdates` with `yay -Q`.

**Comment by Mathew-D** [comment]
We could do something like:
set $updater pamac-manager --updates

or they can change it to this if they want the cli

set $updater /usr/share/sway/scripts/update.sh

or whatever updater they want to use.

then change waybar to something like the following on click:
swaymsg exec \\$updater"

**Comment by xeruf** [comment]
I am using topgrade, very useful!

My current preferred script has some fallback options: https://git.jfischer.org:444/xeruf/dotfiles/src/branch/main/.config/shell/functions#L238

**Review by xeruf — COMMENTED** [review]
Just a note: Since /usr/share/sway/templates/waybar/config.jsonc seems to be a file that affects the user, this commit is not a `chore` by convention: https://karma-runner.github.io/4.0/dev/git-commit-msg.html

And chore seems to have fallen out of favor anyways: https://karma-runner.github.io/6.4/dev/git-commit-msg.html

See also https://www.conventionalcommits.org

**Pull request closed without merging**
