### PR TITLE
feat: streamline screenshot and recording modes

### LINKED ISSUE #106: cleanup screenshot mode
I've decided to open this issue out of frustration that I have when using these modes. First of all I shall say that I really like the idea and the ease-of-use, it's actually very neat, but there are serveral problems with them, I think:
1. These modes aren't "minor" (they don't include the normal mode), which means that when I use them, I cannot use any hotkeys to switch desktops\workspaces\use launcher and many other things I might actually want to do when recording a video, for example
2. Escape is the exit key from the mode, but it's an exit key for basically everything, so, for example, when I want to quit my launcher after starting the record, I actually stop recording instead.
3. In screenshot mode, when you press Area button for example, you can call it several times in a row, which will lead to a faded image. Basically it's a debate if after the screenshot command is executed should we proceed to normal mode or stay in screenshot mode.
4. PrintScreen, the key which most users are very used to isn't mapped. I think it will be nice to make an alternative, mode-less bind at least for making a screenshot with PrintScr, because it's a habit, and this key is made for this anyway :D. On my old setup, I've had these binds for screenshots, maybe it will be a useful starting point (please note I wrote this before encountering Manjaro Sway, so it's not using all the cool possibilities that are available). /usr/share/sway/scripts/grimshot can be used instead as a more universal and consistent solution:
```
#Copy whole screenshot to clipboard
bindsym --to-code Print exec grim - | wl-copy

#Save to HOME
bindsym --to-code Ctrl+Print exec grim ~/Documents/screenshot-"$(date +%s)".png

#Take a screenshot of a window to the clipboard
bindsym --to-code $mod+Print exec grim -g "$(swaymsg -t get_tree | jq -r '.. | select(.focused?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"')" - | wl-copy

#Take a screenshot of the window and save it at HOME
bindsym --to-code Ctrl+$mod+Print exec grim -g "$(swaymsg -t get_tree | jq -r '.. | select(.focused?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"')" ~/Documents/screenshot-"$(date +%s)".png

# Take a screenshot of selected region and save to clipboard
    bindsym --to-code Shift+Print exec grim -g "$(slurp)" - | wl-copy

# Take a screenshot of selected region and save at HOME
    bindsym --to-code Ctrl+Shift+Print exec grim -g "$(slurp)" ~/Documents/screenshot-"$(date +%s)".png
```

### LINKED ISSUE #121: Leaner shutdown menu
We're currently using a fullscreen interface to do that. Suitable alternatives could be a rofi script or (I would prefer) another mode with identical keybinds.

### PR DESCRIPTION
**Pull request by boredland**
closes https://github.com/Manjaro-Sway/manjaro-sway/issues/106
closes https://github.com/Manjaro-Sway/manjaro-sway/issues/121

### CODE REVIEW

**Review by FallenChromium — COMMENTED** [review]
I believe that 5s timeout for temperature module in waybar was a sensible default. As for the screenshot changes, looks good to me at this point, though it can be a good idea to use wf-recorder codecs rather than converting with ffmpeg, and substitude .gif with .webm codec, if it is more efficent. The recording timeout looks weird to me, I am mildly infuriated by this "feature" on Android, but if there's a reason to keep it, then it's cool with me. I really love the way waybar indicators were reworked to update with a push rather than polling, good to see optimizations are made on that front.

**Comment by boredland** [comment]
> The recording timeout looks weird to me, I am mildly infuriated by this "feature" on Android, but if there's a reason to keep it, then it's cool with me.

what do you mean? I think you're either misreading sth or I did sth I did not want to do.

**Comment by boredland** [comment]
https://user-images.githubusercontent.com/4662748/127753877-505b093a-cbcd-4032-acdc-d6b2b593ed81.mp4

**Comment by Mathew-D** [comment]
I might be reading this wrong, but it looks like you are removing the area selection screen shot option ? As there is only notify copy output and notify copy window but no area.

**Comment by boredland** [comment]
> I might be reading this wrong

ya, grim/shots option names are confusing. `window` actually lets you either select windows or draw an area. so its just a better variant since it combines both of them.

**Comment by Mathew-D** [comment]
you might want to update the help section to tell people the change in key bindings from mod+shift+s to printscr.

**Comment by boredland** [comment]
> you might want to update the help section to tell people the change in key bindings from mod+shift+s to printscr.

The help section gets generated ad-hoc as far as I remember what I did there.

**Comment by boredland** [comment]
Yaz: https://www.github.com/Manjaro-Sway/desktop-settings/tree/sway/community%2Fsway%2Fetc%2Fsway%2Fconfig.d%2F95-generate-help.conf

**Comment by FallenChromium** [comment]
Hmm... The recording is kind of broken for me now.
1. After updating the dotfiles, I don't see a hint on how to stop recording (Mod+Esc), and I don't see the waybar indicator. That's because I didn't update my waybar config though
2. Sometimes, only a "pixel" gets recorded rather than a window. That's because the edge between "sliding the selection" and "clicking the window to choose its' dimensions" in slurp is very small. Bad UX, but understandable why it happens
3. I'm not entirely happy that I can't just screenshot\screenrecord everything (relevant for 2+ outputs) with one hotkey and that I have to drag slurp all over the place to select it, but it makes me more mindful on what I'm actually recording, so this is more like a feedback rather than a gripe.
4. It looks to me that audio recording does not work for some reason, I couldn't get any sound from my recordings 🤷🏻‍♂️

**Comment by boredland** [comment]
1. ya, its not a mode anymore, but a waybar module
2. i am not experiencing that issue, perhaps you mouse is much more sensitive than mine?
3. i have multiple outputs too, but recording all of them at once would result in a 2k+4k image that barely anybody will be able to see anything on. tbh: I don't see a reason to have that mode. If you insist, we can add it back tho.
4. that's a bug (change from "--audio" to "-a" for the audio param. fix is on the way.

**Comment by FallenChromium** [comment]
2. Nah, a rather regular mouse. It is a gaming mouse, but the DPI is not high enough. Though yeah, with trackpad that doesn't happen, so maybe mouse settings matter. Again, wasn't that much a complaint, rather a feedback.
3. my 2 x FHD monitors do seem good on screenshots, but I definitely do not insist, I don't screenshot EVERYTHING so often to add additional complexity to shortcuts. I also wanted to propose to make a "fast screenshot" keybind (without going to any mode), but after I got used to press PrtSc+o swiftly, I don't have enough reasons to :D

I am very happy about these changes! Thank you for taking your time to implement this and make a better screenshot\screenrecord mode for everyone of us 👍🏻

**Pull request merged**
