### PR TITLE
chore: fix focussed typos in help

### PR DESCRIPTION
**Pull request by TheNascentMaker**
Since the first thing I saw when installing Sway was several typos in the help overlay, I figured I'd help improve the experience.

### CODE REVIEW

**Review by boredland — APPROVED** [review]
According to the internet, this is more of a taste issue, but well - I don't care ;-)

**Comment by TheNascentMaker** [comment]
I don't care either, as long as they're all the same. Though `focussed` is a weird UK/Australian spelling that I never saw being taught English in Sweden, and it certainly breaks US spellcheckers. Maybe we need to stick those strings in l10n or something so the British can have their weird words to themselves?

**Comment by boredland** [comment]
I think as a German having two s in it sounds more right, because that's similar to how we write it. And cSpell didn't complain. Either way, I'm fine and don't care for legacy English.

**Comment by Mathew-D** [comment]
https://getproofed.com/writing-tips/spelling-tips-focused-or-focussed/

Summary: Focused or Focussed?
“Focused” and “focussed” are two spellings of the same word:

Focused (one “s”) is the standard spelling of this term in modern English.
Focussed (with a double “s”) is a rare variant spelling, although it is more common in British and Australian English than it is in American English. In short, then, it is usually best to stick with “focused.”
lol

**Pull request merged**
