### PR TITLE
fix(sway/autostart): resolve the nm-applet autostart issue

### PR DESCRIPTION
**Pull request by Memoraike**

### CODE REVIEW

**Comment by boredland** [comment]
I think the reason for starting it via dbus-launch was with it starting the tray indicator. Does that change? Otherwise removing will probably have the same effect.

**Comment by Memoraike** [comment]
@boredland deleting dbus-launch does not change this behavior and the tray icon appears. In my environment, nm-applet is not displayed in the tray at all when using dbus-launch.

**Comment by boredland** [comment]
> @boredland deleting dbus-launch does not change this behavior and the tray icon appears. In my environment, nm-applet is not displayed in the tray at all when using dbus-launch.

Then I would say it currently works as intended: with nm-applet as a background job, so we have support for their VPN functionality and all, but not with the tray indicator, as we have a waybar module for that.

**Comment by Memoraike** [comment]
> > @boredland deleting dbus-launch does not change this behavior and the tray icon appears. In my environment, nm-applet is not displayed in the tray at all when using dbus-launch.
> 
> Then I would say it currently works as intended: with nm-applet as a background job, so we have support for their VPN functionality and all, but not with the tray indicator, as we have a waybar module for that.

Yeah, ur right! Previously, I had both of them displayed and I was wondering "why?", in that case, I apologize for taking your time!

**Pull request closed without merging**
