### PR TITLE
Help with hot keys for NWG-Wrapper

### PR DESCRIPTION
**Pull request by MuratovAS**
I made a script for NWG-Wrapper allows you to generate a list of hot keys directly from the SWAY configuration. 
I think this is a useful addition.
Posted by files to "Skel", the help of it will allow the user to make changes to the script. 
Implemented simple interaction logic, the menu is displayed on the 1 minute screen, then hidden. Again it can be called by means of a combination of keys. 
It is worth noting, the script can group hotkeys if they have the same description. 
The script displays all the hot keys having a description, you can add it at the end of the line after "; ###" 
My "Pull Requests" is not completed, the description is only on combinations from the "Modes / Default" file. **I hope for your help with this.** 
P.S. In "Pull Requests" used English and discreet color scheme. 
screenshot

### CODE REVIEW

**Comment by boredland** [comment]
You realize we have those comments above the commands to achieve exactly what you did? The only difference is that you replaced some variables...

**Comment by MuratovAS** [comment]
> You realize we have those comments above the commands to achieve exactly what you did? The only difference is that you replaced some variables...

Your option visualizes what is written in "help.man", a text file with a pre-prepared text.

I suggest add a Help-KeyMap.sh script that allows you to automatically extract information about HotKey and visualize it by NWG-Wrapper. He will find hotkey.
Comments are made in order to concisely describe the actions of the key and allow you to choose which keys should appear in Help.

**Comment by boredland** [comment]
help man is 99% automatically generated, very similar to what you did. It just runs once on every start to speed things up. I like that you added some styling, we should add that mode to our tool too.

**Comment by MuratovAS** [comment]
@boredland 
Sorry, did not carefully looked "95-Generate-Help.conf" and did not know about "SBDP".

**Pull request closed without merging**
