### PR TITLE
feat(waybar): cliphist only if installed

### PR DESCRIPTION
**Pull request by boredland**
resolves parts of https://github.com/Manjaro-Sway/manjaro-sway/issues/175

### CODE REVIEW

**Comment by Mathew-D** [comment]
The right click parts works but I would have to uninstall cliphist to try the optional part.

**Comment by Mathew-D** [comment]
After the purge the cliphist list | wc -l section doesn't seems to update until you restart waybar so it still shows the older amount of items.

**Comment by Mathew-D** [comment]
cliphist just added a new commit which will allow us to use rofi to select just 1 item from the list instead of just purging the whole list.  While we are doing work on it we might want update it and add the option to delete just 1 item so they can remove password and such without remove the whole list.

https://github.com/sentriz/cliphist/issues/18

**Comment by Mathew-D** [comment]
On
``[ -x "$(command -v wl-paste)" ] && [ -x "$(command -v cliphist)" ] && (wl-paste --watch pkill -RTMIN+9 waybar; rm -f ~/.cache/cliphist/db)'
isn't the rm -f ~/.cache/cliphist/db) unneeded as it happens in waybar already?

**Comment by boredland** [comment]
> might want update it 

well - it is not released yet and I don't know how to properly integrate it into our $clipboard command... I suppose we do that in another PR as soon as it is released

> isn't wl-paste --watch pkill -RTMIN+9 waybar; going to restart waybar

no, `pkill -RTMIN+9 waybar` is actually a signal call (signal 9) to waybar and thus we don't need to recheck cliphist on an interval, but just listen to the signal 9 and recheck then. this saves us a lot of processor time.

**Comment by boredland** [comment]
> would have to uninstall cliphist to try the optional part

just did that and works.

**Comment by boredland** [comment]
> isn't the rm -f ~/.cache/cliphist/db) unneeded as it happens in waybar already?

My idea was that we could have a cheap way to run it on logout. But that's not working yet.

**Comment by Mathew-D** [comment]
> I don't know how to properly integrate it into our $clipboard command... 

I would move the purge to the middle click on waybar and move the delete item on right click.  Wouldn't you want to remove one item more often then deleting everything with everything being remove on startup?
and wouldn't something like this do it:

`"swaymsg -q exec cliphist list | rofi -dmenu -theme-str $rofi_theme | cliphist delete-stdin"`

**Comment by boredland** [comment]
> Wouldn't you want to remove one item more often then deleting everything with everything being remove on startup?

so you propose we remove the whole db on startup now and add the single item deletion as soon as that|s released from cliphist side?

**Comment by Mathew-D** [comment]
Wasn't the purging at startup / shutdown one of the items you wanted to add other then making it optional?  Or we could just leave the purge on at middle click and add a note like the following to the readme
To remove the clipboard histroy on startup please add the the following to ~/.cofig/sway/config.d/05-clipboard.conf
`rm ~/.cache/cliphist/db`

Then we add the remove 1 item after the release.

**Comment by Mathew-D** [comment]
Should we use $HOME instead of ~?

**Comment by boredland** [comment]
ya $HOME works, but probably it does not make a lot of sense as is.

**Comment by boredland** [comment]
@Mathew-D I think I found a fine middle ground: you now could opt in to purge on logout by providing `set $purge_cliphist_logout true` in a definition.

**Pull request merged**
