### PR TITLE
use `system-upgrade.sh`

### PR DESCRIPTION
**Pull request by nrth3rnlb**
I find pamac and its GUI in a window manager annoying when TUI is used in almost all places. For this reason I made a script that can update my system at least as fast.

### CODE REVIEW

**Comment by boredland** [comment]
this is not a bad idea, in fact I dreamed about having sth. barebones pamac-like. will try a bit around

**Comment by Mathew-D** [comment]
If we are going to add this, can we make a var so that people that like the current GUI don't have to go looking to switch it back.

**Comment by boredland** [comment]
> If we are going to add this, can we make a var so that people that like the current GUI don't have to go looking to switch it back.

nah, I don't think this one should be the default. just not comparable in terms of features.

**Comment by xeruf** [comment]
I am also constructing a robust upgrade-script that might be interesting for you. It should specifically be able to upgrade Arch/Manjaro-machines that haven't been used in months, which is a hassle by default:

https://git.jfischer.org:444/xeruf/dotfiles/src/branch/main/.config/shell/functions#L215

The diff on this PR got a bit out of hand though.

**Comment by boredland** [comment]
Hi! Thank you all for your contributions and shame on me for not following up. My problem with this was, that I have the strong feeling, that we should not be solving this on our own & that there has to be a "pamac tui" somewhere. But honestly: neither this, nor your script @xeruf looks bad. it is more the "should we be the ones?"-aspect that worries me.

**Comment by xeruf** [comment]
totally agree with you on that, my script outsources the bulk of the work to topgrade and only handles some specials ;) I will use it on all Manjaro- and Arch-machines I deploy and continuously improve it, maybe it will become generally useful at some point.

A similar worry arose as I wrote https://github.com/xeruf/instalee but I just could not find anything like it, and now it has become pretty good :)

**Comment by boredland** [comment]
topgrade looks amazing. should we just ship that one? (will give it a try right now).

**Comment by xeruf** [comment]
well, there's a reason I wrapped it, which as I said relates to being able to upgrade long-untouched devices (at the expense of increased upgrade time as the keys are refreshed daily as of now, just to be safe)

**Comment by boredland** [comment]
> being able to upgrade long-untouched devices


Ya, I know the struggle. For me this sounds nice. Perhaps we can keep both in waybar, your script on right-click and pamac on left click or so.

**Comment by Mathew-D** [comment]
I like the update script, but this pull has lots of conflicts and it should be a user defined variable as to use gui or the cli.. also the script needs a quit command added.  Can we edit this pull so it only adds the script then we can add the option for users to use it.

**Comment by boredland** [comment]
it is only this lil script, isn't it?
```bash
#!/usr/bin/env bash

RELOAD_CMD='yay -Qqu'
REMOVE_CMD='yay -Ru' 
PREVIEW_CMD='yay -Qic'
UPGRADE_CMD='yay --noconfirm -S'

yay -Syy && yay -Qqu | \
  fzf \
  --multi \
  --layout=reverse \
  --header 'Press Ctrl-S to sync, Ctrl-R to remove, Return to upgrade' \
  --preview "$PREVIEW_CMD {} 2>/dev/null" \
  --bind "ctrl-a:select-all" \
  --bind "ctrl-r:execute($REMOVE_CMD {+})+reload($RELOAD_CMD)" \
  --bind "ctrl-s:reload($RELOAD_CMD)" \
  --bind "enter:execute($UPGRADE_CMD {+})+reload($RELOAD_CMD)"
```

**Comment by boredland** [comment]
closed in favor of #125

**Pull request closed without merging**
